[bake]
location = "local"

[applib]
location = "local"

[drives]
location = "local"

[clicklib]
location = "local"

[chroot]
location = "local"

[cyclone]
location = "git"
url = "https://raw.githubusercontent.com/CC-Proot-OS/Cyclone/main/cyclone.toml"
